// Code generated by Kitex v0.5.2. DO NOT EDIT.
package idlmanagement

import (
	idlmanagement "api_gw/service_definitions/kitex_gen/idlmanagement"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler idlmanagement.IDLManagement, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
