// Code generated by Kitex v0.6.1. DO NOT EDIT.
package service2

import (
	service2v1 "api_gw/service_definitions/kitex_gen/service2v1"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler service2v1.Service2, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
