// Code generated by Kitex v0.5.2. DO NOT EDIT.

package service1

import (
	service1v2 "api_gw/service_definitions/kitex_gen/service1v2"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Add(ctx context.Context, req *service1v2.AddRequest, callOptions ...callopt.Option) (r *service1v2.AddResponse, err error)
	Sub(ctx context.Context, req *service1v2.SubRequest, callOptions ...callopt.Option) (r *service1v2.SubResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kService1Client{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kService1Client struct {
	*kClient
}

func (p *kService1Client) Add(ctx context.Context, req *service1v2.AddRequest, callOptions ...callopt.Option) (r *service1v2.AddResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Add(ctx, req)
}

func (p *kService1Client) Sub(ctx context.Context, req *service1v2.SubRequest, callOptions ...callopt.Option) (r *service1v2.SubResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Sub(ctx, req)
}
