// Code generated by Kitex v0.5.2. DO NOT EDIT.

package simpleexample

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "simpleExample/kitex_gen/api"
)

func serviceInfo() *kitex.ServiceInfo {
	return simpleExampleServiceInfo
}

var simpleExampleServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "SimpleExample"
	handlerType := (*api.SimpleExample)(nil)
	methods := map[string]kitex.MethodInfo{
		"echo": kitex.NewMethodInfo(echoHandler, newSimpleExampleEchoArgs, newSimpleExampleEchoResult, false),
		"add":  kitex.NewMethodInfo(addHandler, newSimpleExampleAddArgs, newSimpleExampleAddResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.2",
		Extra:           extra,
	}
	return svcInfo
}

func echoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.SimpleExampleEchoArgs)
	realResult := result.(*api.SimpleExampleEchoResult)
	success, err := handler.(api.SimpleExample).Echo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSimpleExampleEchoArgs() interface{} {
	return api.NewSimpleExampleEchoArgs()
}

func newSimpleExampleEchoResult() interface{} {
	return api.NewSimpleExampleEchoResult()
}

func addHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.SimpleExampleAddArgs)
	realResult := result.(*api.SimpleExampleAddResult)
	success, err := handler.(api.SimpleExample).Add(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSimpleExampleAddArgs() interface{} {
	return api.NewSimpleExampleAddArgs()
}

func newSimpleExampleAddResult() interface{} {
	return api.NewSimpleExampleAddResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Echo(ctx context.Context, req *api.Request) (r *api.Response, err error) {
	var _args api.SimpleExampleEchoArgs
	_args.Req = req
	var _result api.SimpleExampleEchoResult
	if err = p.c.Call(ctx, "echo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Add(ctx context.Context, req *api.AddRequest) (r *api.AddResponse, err error) {
	var _args api.SimpleExampleAddArgs
	_args.Req = req
	var _result api.SimpleExampleAddResult
	if err = p.c.Call(ctx, "add", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
